config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  # gated access
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login

  # content
  resources :artefacts, only: ["index", "show"]
  resources :teams, only: ["show"]
  resources :guides, only: ["index", "show"]
  get "/search", to: "search#results" 
  
  # for fae
  namespace :admin do
    resources :guides
    resources :teams
    resources :artefacts
    resources :collections
  end
  mount Fae::Engine => '/admin'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artefact.rb
class Artefact < ApplicationRecord
  include Fae::BaseModelConcern
  include PgSearch::Model
  multisearchable against: [
    :name, 
    :team_name, 
    :description
  ]

  validates :name, :description, :link, :team, presence: true

  has_fae_image :image

  def team_name
    self.team.name
  end

  def fae_display_field
    name
  end

  belongs_to :team
end

app/models/collection.rb
class Collection < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    name
  end

  belongs_to :team
  has_many :guides
end

app/models/guide.rb
class Guide < ApplicationRecord
  include Fae::BaseModelConcern
  
  include PgSearch::Model
  multisearchable(
    against: [
      :name, 
      :short_description, 
      :body,
      :collection_name, 
      :team_name
    ],
  )

  validates :name, 
    :body, 
    :position, 
    :collection, 
    :short_description, 
  presence: true

  acts_as_list add_new_at: :bottom
  default_scope { order(:position) }

  def collection_name
    self.collection.name
  end

  def description
    self.short_description
  end

  def team_name
    self.collection.team.name
  end
  
  def fae_display_field
    name
  end

  belongs_to :collection
  has_one :team, through: :collection
end

app/models/team.rb
class Team < ApplicationRecord
  include Fae::BaseModelConcern
  def fae_display_field
    name
  end

  has_fae_image :image

  has_many :artefacts

  has_many :collections
  has_many :guides, through: :collections

end

app/controllers/admin/artefacts_controller.rb
module Admin
  class ArtefactsController < Fae::BaseController

    private

    def build_assets
      @item.build_image if @item.image.blank?
    end

  end
end

app/controllers/admin/collections_controller.rb
module Admin
    class CollectionsController < Fae::BaseController
  
    end
  end
  

app/controllers/admin/guides_controller.rb
module Admin
  class GuidesController < Fae::BaseController

  end
end

app/controllers/admin/series_controller.rb
module Admin
  class SeriesController < Fae::BaseController

  end
end

app/controllers/admin/teams_controller.rb
module Admin
  class TeamsController < Fae::BaseController

    private

    def build_assets
      @item.build_image if @item.image.blank?
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    
    def gate_access
        unless cookies.signed[:user_id]
            redirect_to login_path
        end  
    end
end

app/controllers/artefacts_controller.rb
class ArtefactsController < ApplicationController
    before_action :gate_access

    def index
        @teams = Team.order(:name)
    end

    def show
        redirect_to Artefact.find(params[:id]).link
    end
end

app/controllers/google_sign_in/authorizations_controller.rb
require 'securerandom'

class GoogleSignIn::AuthorizationsController < GoogleSignIn::BaseController
  skip_forgery_protection only: :create

  def create
    # restrict ui to offer fg accounts only
    redirect_to login_url(scope: 'openid profile email', state: state, hd: "wearefuturegov.com"),
      flash: { proceed_to: params.require(:proceed_to), state: state }
  end

  private
    def login_url(**params)
      client.auth_code.authorize_url(prompt: 'login', **params)
    end

    def state
      @state ||= SecureRandom.base64(24)
    end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
    before_action :gate_access
    
    def index
        @teams = Team.order(:name)
    end

    def show
        @guide = Guide.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :gate_access
    
    def index
        @teams = Team.order(:name)
        @is_home = true
        @recently_updated = recently_updated
    end

    private

    def recently_updated(num=4)
        list = []
        [Guide, Artefact].each do |m|
            list << m.all.sort_by(&:updated_at).flatten
        end
        list.flatten
            .sort_by(&:updated_at)
            .reverse
            .first(num)
    end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController  
    def new
        render layout: "bare"
    end

    def create
        if token = flash[:google_sign_in_token]
            data = GoogleSignIn::Identity.new(token)
            if data.hosted_domain === "wearefuturegov.com"
                cookies.signed[:user_id] = data.user_id
                redirect_to root_path
            else
                redirect_to login_path
            end
        else
            redirect_to login_path
        end
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :gate_access
    
    def results
        if params["type"].nil?
            @results = PgSearch.multisearch(params["query"])
        else
            @results = PgSearch.multisearch(params["query"])
                .where({
                    :searchable_type => params["type"]
                })
        end
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :gate_access
    
    def show
        @team = Team.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        renderer = ::Redcarpet::Render::HTML.new({
            hard_wrap: true,
            with_toc_data: true
        })
        markdown = ::Redcarpet::Markdown.new(renderer, {
            autolink: true
        })
        markdown.render(text).html_safe
    end


    def toc(text)
        renderer = ::Redcarpet::Render::HTML_TOC.new()
        markdown = ::Redcarpet::Markdown.new(renderer)
        markdown.render(text).html_safe
    end
end

app/helpers/artefacts_helper.rb
module ArtefactsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
    def checked(value)
        if params.has_key?(:type) && params[:type].include?(value)
            "checked"
        else
            ""
        end
    end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin/artefacts/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name
    = fae_input f, :description
    = fae_input f, :link

    = fae_association f, :team

    = fae_image_form f, :image

app/views/admin/guides/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name
    = fae_input f, :body, markdown: true
    = fae_input f, :position
    = fae_input f, :short_description
    = fae_association f, :collection

app/views/admin/guides/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-row
    thead
      tr
        th.th-sortable-handle
        th Name
        th Collection
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td.sortable-handle: i.icon-sort
            td = link_to item.fae_display_field, edit_admin_guide_path(item)
            td = item.collection.name
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="4" No items found

app/views/artefacts/index.html.erb
<% content_for :title, "Artefacts" %>

<%= render "shared/page_header", title: "Artefacts" %>

<main class="page-body">
    <div class="container">

        <% @teams.each do |t| %>
            <h2 class="section-title"><%= t.name %></h2>
            <ul class="three-column-grid">
                <% t.artefacts.each do |a| %>
                    <%= render "shared/artefact", artefact: a %>
                <% end %>
            </ul>
        <% end %>

    </div>
</main>