config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  # gated access
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login

  # content
  resources :artefacts, only: ["index", "show"]
  resources :teams, only: ["show"]
  resources :guides, only: ["index", "show"]
  get "/search", to: "search#results" 
  
  # for fae
  namespace :admin do
    resources :guides
    resources :teams
    resources :artefacts
    resources :collections
  end
  mount Fae::Engine => '/admin'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artefact.rb
class Artefact < ApplicationRecord
  include Fae::BaseModelConcern
  include PgSearch::Model
  multisearchable against: [
    :name, 
    :team_name, 
    :description
  ]

  validates :name, :description, :link, :team, presence: true

  has_fae_image :image

  def team_name
    self.team.name
  end

  def fae_display_field
    name
  end

  belongs_to :team
end

app/models/collection.rb
class Collection < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    name
  end

  belongs_to :team
  has_many :guides
end

app/models/guide.rb
class Guide < ApplicationRecord
  include Fae::BaseModelConcern
  
  include PgSearch::Model
  multisearchable(
    against: [
      :name, 
      :short_description, 
      :body,
      :collection_name, 
      :team_name
    ],
  )

  validates :name, 
    :body, 
    :position, 
    :collection, 
    :short_description, 
  presence: true

  acts_as_list add_new_at: :bottom
  default_scope { order(:position) }

  def collection_name
    self.collection.name
  end

  def description
    self.short_description
  end

  def team_name
    self.collection.team.name
  end
  
  def fae_display_field
    name
  end

  belongs_to :collection
  has_one :team, through: :collection
end

app/models/team.rb
class Team < ApplicationRecord
  include Fae::BaseModelConcern
  def fae_display_field
    name
  end

  has_fae_image :image

  has_many :artefacts

  has_many :collections
  has_many :guides, through: :collections

end

app/controllers/admin/artefacts_controller.rb
module Admin
  class ArtefactsController < Fae::BaseController

    private

    def build_assets
      @item.build_image if @item.image.blank?
    end

  end
end

app/controllers/admin/guides_controller.rb
module Admin
  class GuidesController < Fae::BaseController

  end
end

app/controllers/admin/series_controller.rb
module Admin
  class SeriesController < Fae::BaseController

  end
end

app/controllers/admin/teams_controller.rb
module Admin
  class TeamsController < Fae::BaseController

    private

    def build_assets
      @item.build_image if @item.image.blank?
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    
    def gate_access
        unless cookies.signed[:user_id]
            redirect_to login_path
        end  
    end
end

app/controllers/artefacts_controller.rb
class ArtefactsController < ApplicationController
    before_action :gate_access

    def index
        @teams = Team.order(:name)
    end

    def show
        redirect_to Artefact.find(params[:id]).link
    end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
    before_action :gate_access
    
    def index
        @teams = Team.order(:name)
    end

    def show
        @guide = Guide.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :gate_access
    
    def index
        @teams = Team.order(:name)
        @is_home = true
        @recently_updated = recently_updated
    end

    private

    def recently_updated(num=4)
        list = []
        [Guide, Artefact].each do |m|
            list << m.all.sort_by(&:updated_at).flatten
        end
        list.flatten
            .sort_by(&:updated_at)
            .reverse
            .first(num)
    end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController  
    def new
        render layout: "bare"
    end

    def create
        if token = flash[:google_sign_in_token]
            data = GoogleSignIn::Identity.new(token)
            if data.hosted_domain === "wearefuturegov.com"
                cookies.signed[:user_id] = data.user_id
                redirect_to root_path
            else
                redirect_to login_path
            end
        else
            redirect_to login_path
        end
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :gate_access
    
    def results
        if params["type"].nil?
            @results = PgSearch.multisearch(params["query"])
        else
            @results = PgSearch.multisearch(params["query"])
                .where({
                    :searchable_type => params["type"]
                })
        end
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :gate_access
    
    def show
        @team = Team.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        renderer = ::Redcarpet::Render::HTML.new({
            hard_wrap: true,
            with_toc_data: true
        })
        markdown = ::Redcarpet::Markdown.new(renderer, {
            autolink: true
        })
        markdown.render(text).html_safe
    end


    def toc(text)
        renderer = ::Redcarpet::Render::HTML_TOC.new()
        markdown = ::Redcarpet::Markdown.new(renderer)
        markdown.render(text).html_safe
    end
end

app/helpers/artefacts_helper.rb
module ArtefactsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
    def checked(value)
        if params.has_key?(:type) && params[:type].include?(value)
            "checked"
        else
            ""
        end
    end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<% content_for :title, "FutureGov Knowledge" %>

<section class="hero">
    <div class="hero__inner container">
        <div class="hero__main-content">
            <h1 class="hero__headline">Learn from our best work</h1>
            <p class="hero__strapline">Explore examples of work, see templates to get started quickly, and read guides.</p>
            <form class="search-form" method="get" action="/search">
                <input name="query" placeholder="Search..." class="search-form__input" required>
                <button class="search-form__button"><%= image_tag "search.svg" %></button>
            </form>
        </div>
        <aside class="hero__sidebar">
            <h2 class="hero__sidebar-title">Recently changed</h2>
            <ul class="recent-changes">
                <% @recently_updated.each do |recent| %>
                    <li class="recent-changes__item">
                        <%= link_to recent.name, recent, class: "recent-changes__link" %>
                    </li>
                <% end %>
            </ul>
        </aside>
    </div>
</section>

<section class="tiles">
    <div class="tiles__inner container">
        <a class="tile" href="<%= artefacts_path %>">
            <h3 class="tile__headline">Artefacts</h3>
            <p class="tile__abstract">Examples of our best work, mostly with original files suitable for re-use.</p>
        </a>
        <a class="tile" href="<%= guides_path %>">
            <h3 class="tile__headline">Guides</h3>
            <p class="tile__abstract">Examples of our best work, mostly with original files suitable for re-use.</p>
        </a>
        <a class="tile" href="http://handbook.wearefuturegov.com">
            <h3 class="tile__headline">Handbook</h3>
            <p class="tile__abstract">Understand our people and workplace policies.</p>
        </a>
        <%# Extras %>
        <a class="tile" href="https://fg-tech.herokuapp.com/">
            <h3 class="tile__headline">Technology</h3>
            <p class="tile__abstract">Examples and definitions of technology we've come across.</p>
        </a>
        <a class="tile tile--coming-soon">
            <h3 class="tile__headline">Templates</h3>
            <p class="tile__abstract">Coming soon...</p>
        </a>
    </div>
</section>

<section class="explore-by-team">
    <div class="explore-by-team__inner container">
        <h3 class="explore-by-team__title">Explore by team</h3>
        <div class="explore-by-team__filmstrip">
            <% @teams.each do |t| %>
                <a class="explore-by-team__tile" href="<%= team_path(t) %>">
                    <%= image_tag t.image.asset.home.url, class: "explore-by-team__image" %>
                    <h2 class="explore-by-team__name"><%= t.name %></h2>
                </a>
            <% end %>
        </div>
    </div>
</section>

<section class="contribute">
    <div class="container">
        <div class="contribute__inner">
            Something missing? Suggest a change or addition on <a href="https://app.slack.com/client/T024ZJU1Z/CL11GC5NC"><strong>#knowledge-management</strong></a>.
        </div>
    </div>
</section>

app/views/search/results.html.erb
<form method="get" action="/search" id="search-form">
    <section class="search-results-header">
        <div class="container">
            <h1 class="search-results-header__title">Results</h1>
            <div class="search-form search-form--dark">
                <input value="<%= params["query"] %>" name="query" placeholder="Search..." class="search-form__input" required>
                <button class="search-form__button"><%= image_tag "search-dark.svg" %></button>            
            </div>
        </div>
    </section>

    <main class="page-body">
        <div class="container">

            <div class="two-column-layout">
                <div class="two-column-layout__main-content">
                    <ul class="search-results">
                        <% @results.each do |result| %>
                        <li class="search-result">
                            <a class="search-result__title" href="<%= url_for result.searchable %>"><%= result.searchable.name %></a>
                            <p class="search-result__description"><%= result.searchable.description %></p>
                            <p class="search-result__meta"><%= result.searchable_type %>  ·  <%= result.searchable.team.name %></p>
                        </li>
                        <% end %>
                    </ul>
                </div>
                
                <aside class="two-column-layout__sidebar">
                    <div class="ruled-area ruled-area--markdown">
                            <h3 class="ruled-area__header">Content type</h3>
                            <div>
                                <input class="checkbox" type="checkbox" name="type[]" value="Guide" id="type-guide" onclick="updateSearch()" <%= checked("Guide") %>>
                                <label for="type-guide">Guides</label>
                            </div>
                            <div>
                                <input class="checkbox" type="checkbox" name="type[]" value="Artefact" id="type-artefact" onclick="updateSearch()" <%= checked("Artefact") %>>
                                <label for="type-artefact">Artefacts</label>
                            </div>
                    </div>
                </aside>

            </div>

        </div>
    </main>
</form>